[김기현] add: main_page view 작성
wecode-bootcamp-korea/30-1st-CaKoo-backend pull request #5
Opened 2022-03-03 11:57 UTC by tanonkim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지 뷰 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인페이지 뷰 작성
- 이름, 설명, 이미지, 사이즈, 할인율, 가격을 맞춰 POST하고 GET
- 제품 id에 해당하는 가격 처리 로직 구현
- 제품 size에 해당하는 size 처리
- 값을 받아올 수 없을 때 빈값으로 들고올 수 있도록 처리 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 제품의 id값과 해당 제품과 연결되는 사이즈 id가 하나라도 매치가 되지 않는다면  index out of range 에러가 발생하는 것을 새겼습니다.
![image](https://user-images.githubusercontent.com/60570733/156559893-b6680cee-7a26-48b5-9769-713805a8be94.png)
- 각 제품의 가격을 매기긴 위해서 id를 지정해주어야 함을 다시 느꼈습니다.
<br />

## :: 기타 질문 및 특이 사항

2022-03-04 02:55 UTC, Kang-kyunghun requested changes

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/urls.py
> +    path("/list", ListView.as_view()),
```suggestion
    path("", ListView.as_view()),
```
RESTful API 세션 때 들으셨겠지만, /products 로도 제품들 정보 충분히 나타낼 수 있습니다.

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
- 제품을 등록하는 기능은 일반 유저가 하는 기능이 아닌데(admin에서 해야되는) 추가한 이유가 있을까요?
- 그리고 만약에 등록이 가능하다고 해도 로그인 한 유저가 모두 등록할 수 있는 것이 아니라, 특정 권한이 있는 사람만 등록할 수 있게 해야할 것 같은데, 제가 모르는 기획적인 부분이 있으면 코멘트로 남겨주세요.

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/views.py
> +class ListView(View):
```suggestion
class ProductListView(View):
```
or
```suggestion
class ProductsView(View):
```
해당 View가 어떤 자원에 대한 View인지를 명확히 나타낼 수 있는 class 명으로 바꿔주세요.

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/views.py
> +        products    = Product.objects.filter()
filter에 아무 조건이 없던데 나중을 위해 일단 사용한 것인가요??

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/views.py
> +        productsize = ProductSize.objects.filter()
prodcut_size 정보는 for문 안에서 특정되는 product로부터 가져와 주세요.

2022-03-04 02:55 UTC, Kang-kyunghun commented on products/views.py
> +            )
list comprehension으로 바꿔보세요.

2022-03-04 03:37 UTC, tanonkim commented on products/urls.py
> +    path("/list", ListView.as_view()),
넵! 충분히 인지하겠습니다!

2022-03-04 03:40 UTC, tanonkim commented on products/views.py
> +class ListView(View):
넵! 확인했습니다~

2022-03-04 04:33 UTC, tanonkim commented on products/views.py
> +        products    = Product.objects.filter()
all로 수정완료했습니다!
이것 저것 넣어보다가 filter로 되었습니다.

2022-03-04 04:34 UTC, tanonkim commented on products/views.py
> +        productsize = ProductSize.objects.filter()
넵!

2022-03-04 04:39 UTC, tanonkim commented on products/views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
네 경훈님께서 말씀하신대로 유저가 아닌 관리자가 상품을 넣도록 해야하기에 post를 하였는데, 이렇게 되면 admin을 위한 사이트 제작 등이 필요해보입니다.

결론은 필요없다고 생각되어 삭제완료하였습니다.

2022-03-04 06:02 UTC, tanonkim commented on products/views.py
> +            )
넵 성능과 더 직관적으로 보일 수 있겠끔 수정완료하였습니다.

2022-03-06 08:30 UTC, Kang-kyunghun requested changes

2022-03-06 08:30 UTC, Kang-kyunghun commented on products/views.py
> +            sort     = request.GET.get('sort', "id")
ordering과 sort의 차이가 뭘까요?

2022-03-06 08:30 UTC, Kang-kyunghun commented on products/views.py
> +
sort와 ordering을 같이 생각해 보면 좋을 것 같네요.

2022-03-06 08:30 UTC, Kang-kyunghun commented on products/views.py
> +            page     = int(request.GET.get('page', 0))
```suggestion
            offset     = int(request.GET.get('page', 0))
```
아래 로직을 보니 offset이 더 맞는 의미인 것 같네요.

2022-03-06 08:30 UTC, Kang-kyunghun commented on products/views.py
> +                "discount_price" : int(ProductSize.objects.filter(product=product).first().price) * float(product.discount_rate)
discount_rate을 보내주는데, 다시 할인 가격을 보내주는 이유가 있나요?
(백엔드에서 계산하기로 한 건가요?)

2022-03-06 08:31 UTC, Kang-kyunghun commented
Created_at에 따라 뭐가 달라지는 정확히 이해하기 어렵습니다. 조금만 더 자세히 설명 부탁드립니다.

2022-03-06 12:15 UTC, tanonkim commented on products/views.py
> +            page     = int(request.GET.get('page', 0))
네 확인하였습니다!

2022-03-06 12:15 UTC, tanonkim commented on products/views.py
> +                "discount_price" : int(ProductSize.objects.filter(product=product).first().price) * float(product.discount_rate)
네! 프론트와 상의해서 백엔드에서 계산해서 보내주기로 했습니다.
할인율, 가격, 할인된 가격 모두 백엔드에서 처리하기로 했습니다.

2022-03-06 15:26 UTC, tanonkim commented on products/views.py
> +            sort     = request.GET.get('sort', "id")
order는 단순히 주어진 데이터에 오름차순인지 내림차순인지 정의하는 변수이고
 sort는 그 기준이 어떤 컬럼인지 정의하는 변수라고 이해했습니다!

2022-03-06 15:50 UTC, tanonkim commented on products/views.py
> +
네! sort에서 가격별로 정렬할 수 있다고 생각합니다.
여기서 blocked된 이슈가 있는데 sort값으로 price를 가져가기 위해선 Product에서 물고 있는 price가 필요합니다.
 하지만 현재 모델링이선 price는 중간테이블에 물고 있고 Product로 값을 끌고 오고 있기 때문에 중간테이블로 값을 못끌고 오고 있으며 Field에러를 내고 있습니다. 따라서 Ordering을 추가해 Price ordering을 진행하고 있는데,  price밸류 값을 가지고 있는 중간 테이블인 ProductSize로 부터 값을 끌고 올 수 있는 방법이 있는지 궁금합니다!!!!

2022-03-06 15:51 UTC, tanonkim commented on products/views.py
> +
- 필드 에러
<img width="1076" alt="스크린샷 2022-03-07 오전 12 43 53" src="https://user-images.githubusercontent.com/60570733/156930687-e9d8a500-0ed3-4b6a-80ac-f8f60150419a.png">
- 모델링
![스크린샷 2022-03-07 오전 12 50 08](https://user-images.githubusercontent.com/60570733/156930710-a896fc92-35f0-4f82-8328-6503db5c77a8.png)

2022-03-09 01:50 UTC, Kang-kyunghun commented
LGTM~!!

2022-03-09 01:50 UTC, merged