[박건규] add : products datail page view
wecode-bootcamp-korea/30-1st-CaKoo-backend pull request #6
Opened 2022-03-04 05:21 UTC by Pbang91

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세페이지와 연결할 view를 작성하고 있습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상세 페이지 요청 처리
- 리스트 페이지에서 상세 페이지로 넘어올 시 uri에 넘어오는 상품 id를 받아줘서 필터링 해주는 작업 진행
- 상품 상세 페이지에서 기본적으로 보여주는 내용은 해당 상품의 이름, 한줄설명, 사진, 설명사진, 사이즈 종류, 최소 사이즈(Mini)의 가격을 기본적으로 보여주고 있습니다.
- 상세 페이지에서 케이크의 사이즈를 선택할 때를 대비한 분기점을 적용하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 기본적으로 보여줘야하는 내용과 분기처리를 해서 보여줘야 하는 내용을 고민할 수 있었습니다.
- 해당 상품의 Id로 받을 수 있는 방법을 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다....
- 
![image](https://user-images.githubusercontent.com/90089275/156704221-0510eba9-0552-466b-b9a1-9da62a3831a8.png)
![image](https://user-images.githubusercontent.com/90089275/156704327-a39f8ab2-3bd3-4d5c-969c-bfe98ef8d0ba.png)

2022-03-04 08:15 UTC, Kang-kyunghun requested changes

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/urls.py
> +    path("/product/<id>", ProductDetailView.as_view()),
```suggestion
    path("/product/<int:product_id>", ProductDetailView.as_view()),
```
- data type을 정확하게 정해줴요.
- 어떤 리소스의 id인지 명확하게 해주는 것이 좋습니다.

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +    @login_decorator
로그인을 하지 않으면 상세 페이지를 볼 수 없는 건가요?

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({"message" : "INVALID_PRODUCT"})
```suggestion
            return JsonResponse({"message" : "INVALID_PRODUCT"}, status=404)
```

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +    def post(self, request, id):
```suggestion
    def get(self, request, id):
```
상세 데이터 조회 이므로 get method를 사용해 주세요.

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +            data               = json.loads(request.body)
get method에는 body가 존재하지 않습니다.

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +            information_images = product.informationimages.filter(product = product)
```suggestion
            product_images     = product.productimages.all()
            information_images = product.informationimages.all()
```
product를 통해서 이미지를 찾는 부분은 잘 했습니다.
하나만 고치자면, 이미 특정 지은 product로부터 이미지를 찾기 시작했기 때문에 filter가 걸렸다고 생각하시면 좋을 것 같습니다.
제가 리뷰 드린 코드를 한 번 shell에서 테스트 해보세요.

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +                return JsonResponse({"message" : result}, status = 200)
size_id를 왜 받는지 잘 모르겠네요.
해당 product가 가지고 있는 sizs 옵션들을 같이 데이터에 넣어주면 될 것 같습니다.

2022-03-04 08:15 UTC, Kang-kyunghun commented on products/views.py
> +                product_urls.append(image.url)
list comprehension을 사용해 보세요.

2022-03-04 12:22 UTC, Pbang91 commented on products/urls.py
> +    path("/product/<id>", ProductDetailView.as_view()),
넵 변경했습니다

2022-03-04 12:23 UTC, Pbang91 commented on products/views.py
> +    @login_decorator
로그인 여부와 관계없이 볼 수 있도록 데코 제외했습니다

2022-03-04 12:23 UTC, Pbang91 commented on products/views.py
> +            return JsonResponse({"message" : "INVALID_PRODUCT"})
status code 추가했습니다.

2022-03-04 12:23 UTC, Pbang91 commented on products/views.py
> +    def post(self, request, id):
get 메소드로 변경하여 진행했습니다.

2022-03-04 12:23 UTC, Pbang91 commented on products/views.py
> +                product_urls.append(image.url)
컴프리헨션으로 진행해보았습니다!

2022-03-04 12:24 UTC, Pbang91 commented on products/views.py
> +            data               = json.loads(request.body)
넵

2022-03-04 12:24 UTC, Pbang91 commented on products/views.py
> +            information_images = product.informationimages.filter(product = product)
넵 확인해본 후 해당 코드처럼 수정했습니다.

2022-03-06 08:25 UTC, Kang-kyunghun requested changes

2022-03-06 08:25 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status = 400)
keyerror가 나오는 상황이 없는 것 같습니다. 제거해 주셔도 될 것 같습니다.

2022-03-06 08:25 UTC, Kang-kyunghun commented on products/views.py
> +            size_price         = [{'size' : product_size.size.size , 'price' : product_size.price} for product_size in product_sizes]
다시 변수에 안 담고 아래와 같이 바로 사용해도 좋을 것 같네요.
```suggestion
        try:
            product            = Product.objects.get(id = product_id)
            product_urls       = [image.url for image in product.productimages.all()]
            information_urls   = [information_image.url for information_image in product.informationimages.all()]
            size_price         = [{
                'size' : product_size.size.size , 
                'price' : product_size.price
            } for product_size in product.productsizes.all()]
```

2022-03-06 08:25 UTC, Kang-kyunghun commented on products/views.py
> +                'base_price'         : product_sizes[0].price,
기준 가격이 무조건 첫번째로 등록된 가격이가요?
조금 더 명확한 기준이면 좋을 것 같아요. 예를 들어 최저가 또는 최저가 아니면 특정 사이즈의 가격이던가요.

2022-03-06 08:26 UTC, Kang-kyunghun commented
정확히 어떤 함수의 로직이 길다고 느끼시나요?

2022-03-06 14:29 UTC, Pbang91 commented on products/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status = 400)
넵 json을 안받고 있으니 지웠습니다!

2022-03-06 14:29 UTC, Pbang91 commented on products/views.py
> +            size_price         = [{'size' : product_size.size.size , 'price' : product_size.price} for product_size in product_sizes]
넵 바로 컴프리헨션에서 진행했습니다!

2022-03-06 14:29 UTC, Pbang91 commented on products/views.py
> +                'base_price'         : product_sizes[0].price,
사이즈가 미니일 때 베이스 프라이스를 받아주게 설정했습니다!

2022-03-07 09:30 UTC, Kang-kyunghun requested changes

2022-03-07 09:30 UTC, Kang-kyunghun commented on products/views.py
> +                } for product_size in product.productsizes.all()]
-  변수명 size_price - > sizes
- size_id 추가

```suggestion
            sizes         = [{
                'size_id' : product_size.size.id,
                'size'     : product_size.size.size,
                'price'    : product_size.price
            } for product_size in product.productsizes.all()]
```

2022-03-07 09:30 UTC, Kang-kyunghun commented on products/views.py
> +                    base_price = i['price']
이 부분의 역할이 잘 이해가 안 되네요.
내일 오전에 설명해 주세요.

2022-03-07 11:23 UTC, Pbang91 commented on products/views.py
> +                } for product_size in product.productsizes.all()]
id를 추가했습니다.

2022-03-07 11:25 UTC, Pbang91 commented on products/views.py
> +                    base_price = i['price']
사이즈 키가 mini인 것을 base_price 로 지정해주려고 했는데, 가장 작은 가격을 설정해주는 코드로 변경했습니다.

2022-03-08 04:27 UTC, Pbang91 commented
지원님 carts local merge 후 base_price를 annotate 함수로 변경하였습니다.

2022-03-09 03:55 UTC, Kang-kyunghun commented
LGTM~!!

2022-03-09 03:56 UTC, merged